name: "Push an image"
on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Architectures'
        required: true
        default: 'linux/arm/v7,linux/amd64,linux/arm64'
      image:
        description: 'Image to build'
        required: true
        default: 'dovecot'
env:
  IMAGE_VERSION: r${{ github.run_number }}
  IMAGE_SELECTED: ${{ github.event.inputs.image }}
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.inputs.image }}
  IMAGE_ARG: ${{ github.event.inputs.arch }}
  REGISTRY: ghcr.io
jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@a9794064588be971151ec5e7144cb535bcb56e36
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: ${{ github.event_name != 'pull_request' }}
        context: ${{ env.IMAGE_SELECTED }}
        platforms: ${{ env.IMAGE_ARG }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
